stages:
  - setup_db_solr
  - setup_web_and_test
  - deconstruct


setup_db_solr:
  stage: setup_db_solr
  script:
  - docker-compose -f docker-compose.yml up -d
  tags: 
    - shell
    
setup_web_and_test:
  stage: setup_web_and_test
  image: ruby:2.4.5
  script:
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - cp mv bin/phantomjs /usr/local/bin/
  - bundle install
  - bundle exec rspec --color --format documentation
  tags:
    - docker
    
deconstruct:
  stage: deconstruct
  script:
  - docker-compose rm -fs solr db
  when: always
  tags:
   - shell
