stages:
  - setup_db_solr
  - setup_web_and_test
  - deconstruct


setup_db_solr:
  stage: setup_db_solr
  script:
  - docker run --name solr --expose 8983 -d -v provision:/data -w /data solr:6 /bin/bash provision/solr-entrypoint.sh
  - docker run --name db --expose 5432 -d postgres
  - docker ps
  tags: 
    - shell
    
setup_web_and_test:
  stage: setup_web_and_test
  image: ruby:2.4.5
  script:
  - wget --quiet https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /bin/
  - apt-get update -qq && apt-get -y install nodejs
  - bundle install
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rspec --color --format documentation
  tags:
    - docker
    
deconstruct:
  stage: deconstruct
  script:
  - docker-compose rm -fs solr db
  when: always
  tags:
   - shell
