stages:
  - setup_db_solr
  - setup_web_and_test
  - deconstruct


setup_db_solr:
  stage: setup_db_solr
  script:
  - docker network create dlg_testing
  - docker run -d --name solr --expose 8983 -v `pwd`:/data -w /data --network dlg_testing --network-alias=solr --entrypoint "/bin/bash" solr:6 /data/provision/solr-entrypoint.sh
  - docker run --name db --expose 5432 --network dlg_testing --network-alias=db -d postgres
  - docker ps
  tags: 
    - shell
    
setup_web_and_test:
  stage: setup_web_and_test
  image: ruby:2.4.5
  services:
  - alias "web"
  script:
  - wget --quiet https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs /bin/
  - apt-get update -qq && apt-get -y install nodejs
  - bundle install
  - bundle exec rake db:setup RAILS_ENV=test
  - bundle exec rspec --color --format documentation
  tags:
    - docker
    
janky_experiment:
  stage: setup_web_and_test
  script:
  - docker network connect dlg_testing `docker ps | awk 'NR==2 {print $1}'`
  when: delayed
  start_in: 10 seconds
  tags:
  -  shell

deconstruct:
  stage: deconstruct
  script:
  - docker rm -f solr db
  - docker network rm dlg_testing
  when: always
  tags:
   - shell
