development:
  adapter: solr
  url: <%= "http://127.0.0.1:8983/solr/blacklight-core" %>
test: &test
  adapter: solr
  url: <%= "http://127.0.0.1:8983/solr/test-blacklight-core" %>
staging:
  adapter: solr
  url: <%= "http://solrcloud.galib.uga.edu:8983/solr/meta-prod" %>
production:
  adapter: solr
  url: <%= "http://solrcloud.galib.uga.edu:8983/solr/meta-prod" %>